remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll

title:              Oldman's Blog
email:              einzwars@naver.com
description:        노인의 블로그
author:             노인
baseurl:            ""
url:                "https://einzwars.github.io"

# Social Profiles
twitter_username:   
github_username:    einzwars
facebook_username: 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
